# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cuartos.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Cuartos(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1047, 595)
        Dialog.setStyleSheet("background-image: url(:/grupos/grupos.jpg);")
        self.CASA = QtWidgets.QLabel(Dialog)
        self.CASA.setGeometry(QtCore.QRect(440, 510, 321, 41))
        self.CASA.setStyleSheet("color: rgb(255, 255, 255);")
        self.CASA.setObjectName("CASA")
        self.FOO = QtWidgets.QLabel(Dialog)
        self.FOO.setGeometry(QtCore.QRect(10, 510, 161, 41))
        self.FOO.setStyleSheet("color: rgb(255, 255, 255);")
        self.FOO.setObjectName("FOO")
        self.ASOTRU = QtWidgets.QLabel(Dialog)
        self.ASOTRU.setGeometry(QtCore.QRect(10, 0, 151, 111))
        self.ASOTRU.setStyleSheet("border-image: url(:/asoaje/asotrujillana.jpeg);")
        self.ASOTRU.setText("")
        self.ASOTRU.setObjectName("ASOTRU")
        self.LICHESS = QtWidgets.QLabel(Dialog)
        self.LICHESS.setGeometry(QtCore.QRect(830, 0, 151, 111))
        self.LICHESS.setStyleSheet("border-image: url(:/lichess/lichess.jpeg);")
        self.LICHESS.setText("")
        self.LICHESS.setObjectName("LICHESS")
        self.pushButton_sig = QtWidgets.QPushButton(Dialog)
        self.pushButton_sig.setGeometry(QtCore.QRect(870, 510, 111, 41))
        self.pushButton_sig.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_sig.setObjectName("pushButton_sig")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 120, 941, 391))
        self.label.setStyleSheet("border-image: url(:/cuartos/cuartos.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(720, 220, 161, 31))
        self.label_3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_A3 = QtWidgets.QLabel(Dialog)
        self.label_A3.setGeometry(QtCore.QRect(880, 220, 31, 31))
        self.label_A3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A3.setText("")
        self.label_A3.setObjectName("label_A3")
        self.label_A4 = QtWidgets.QLabel(Dialog)
        self.label_A4.setGeometry(QtCore.QRect(880, 260, 31, 31))
        self.label_A4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A4.setText("")
        self.label_A4.setObjectName("label_A4")
        self.label_A2 = QtWidgets.QLabel(Dialog)
        self.label_A2.setGeometry(QtCore.QRect(110, 260, 31, 31))
        self.label_A2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_A2.setText("")
        self.label_A2.setObjectName("label_A2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 260, 161, 31))
        self.label_2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(140, 220, 161, 31))
        self.label_1.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.label_A1 = QtWidgets.QLabel(Dialog)
        self.label_A1.setGeometry(QtCore.QRect(110, 220, 31, 31))
        self.label_A1.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A1.setText("")
        self.label_A1.setObjectName("label_A1")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(720, 260, 161, 31))
        self.label_4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(720, 420, 161, 31))
        self.label_7.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_A3_2 = QtWidgets.QLabel(Dialog)
        self.label_A3_2.setGeometry(QtCore.QRect(880, 420, 31, 31))
        self.label_A3_2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A3_2.setText("")
        self.label_A3_2.setObjectName("label_A3_2")
        self.label_A4_2 = QtWidgets.QLabel(Dialog)
        self.label_A4_2.setGeometry(QtCore.QRect(880, 460, 31, 31))
        self.label_A4_2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A4_2.setText("")
        self.label_A4_2.setObjectName("label_A4_2")
        self.label_A2_2 = QtWidgets.QLabel(Dialog)
        self.label_A2_2.setGeometry(QtCore.QRect(110, 460, 31, 31))
        self.label_A2_2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_A2_2.setText("")
        self.label_A2_2.setObjectName("label_A2_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(140, 460, 161, 31))
        self.label_6.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(140, 420, 161, 31))
        self.label_5.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_A1_2 = QtWidgets.QLabel(Dialog)
        self.label_A1_2.setGeometry(QtCore.QRect(110, 420, 31, 31))
        self.label_A1_2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A1_2.setText("")
        self.label_A1_2.setObjectName("label_A1_2")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(720, 460, 161, 31))
        self.label_8.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(250, 380, 161, 31))
        self.label_11.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_A3_3 = QtWidgets.QLabel(Dialog)
        self.label_A3_3.setGeometry(QtCore.QRect(220, 380, 31, 31))
        self.label_A3_3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A3_3.setText("")
        self.label_A3_3.setObjectName("label_A3_3")
        self.label_A4_3 = QtWidgets.QLabel(Dialog)
        self.label_A4_3.setGeometry(QtCore.QRect(760, 380, 31, 31))
        self.label_A4_3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A4_3.setText("")
        self.label_A4_3.setObjectName("label_A4_3")
        self.label_A2_3 = QtWidgets.QLabel(Dialog)
        self.label_A2_3.setGeometry(QtCore.QRect(760, 300, 31, 31))
        self.label_A2_3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_A2_3.setText("")
        self.label_A2_3.setObjectName("label_A2_3")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(600, 300, 161, 31))
        self.label_10.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(250, 300, 161, 31))
        self.label_9.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_A1_3 = QtWidgets.QLabel(Dialog)
        self.label_A1_3.setGeometry(QtCore.QRect(220, 300, 31, 31))
        self.label_A1_3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A1_3.setText("")
        self.label_A1_3.setObjectName("label_A1_3")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(600, 380, 161, 31))
        self.label_12.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_A2_4 = QtWidgets.QLabel(Dialog)
        self.label_A2_4.setGeometry(QtCore.QRect(680, 340, 31, 31))
        self.label_A2_4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_A2_4.setText("")
        self.label_A2_4.setObjectName("label_A2_4")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(520, 340, 161, 31))
        self.label_14.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(330, 340, 161, 31))
        self.label_13.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_A1_4 = QtWidgets.QLabel(Dialog)
        self.label_A1_4.setGeometry(QtCore.QRect(300, 340, 31, 31))
        self.label_A1_4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A1_4.setText("")
        self.label_A1_4.setObjectName("label_A1_4")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(80, 220, 21, 22))
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(80, 270, 21, 22))
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(920, 220, 21, 22))
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_4.setGeometry(QtCore.QRect(920, 260, 21, 22))
        self.radioButton_4.setText("")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_5.setGeometry(QtCore.QRect(80, 420, 21, 22))
        self.radioButton_5.setText("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_6.setGeometry(QtCore.QRect(80, 460, 21, 22))
        self.radioButton_6.setText("")
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_7.setGeometry(QtCore.QRect(920, 420, 21, 22))
        self.radioButton_7.setText("")
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_8.setGeometry(QtCore.QRect(920, 460, 21, 22))
        self.radioButton_8.setText("")
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_9.setGeometry(QtCore.QRect(190, 300, 21, 22))
        self.radioButton_9.setText("")
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_10.setGeometry(QtCore.QRect(800, 300, 21, 22))
        self.radioButton_10.setText("")
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_11.setGeometry(QtCore.QRect(190, 380, 21, 22))
        self.radioButton_11.setText("")
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_12.setGeometry(QtCore.QRect(800, 380, 21, 22))
        self.radioButton_12.setText("")
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_13.setGeometry(QtCore.QRect(270, 340, 21, 22))
        self.radioButton_13.setText("")
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_14.setGeometry(QtCore.QRect(720, 340, 21, 22))
        self.radioButton_14.setText("")
        self.radioButton_14.setObjectName("radioButton_14")
        self.label_campeon_2 = QtWidgets.QLabel(Dialog)
        self.label_campeon_2.setGeometry(QtCore.QRect(430, 230, 161, 41))
        self.label_campeon_2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_campeon_2.setText("")
        self.label_campeon_2.setObjectName("label_campeon_2")
        self.label_campeon = QtWidgets.QLabel(Dialog)
        self.label_campeon.setGeometry(QtCore.QRect(400, 230, 31, 41))
        self.label_campeon.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_campeon.setText("")
        self.label_campeon.setObjectName("label_campeon")
        self.label.raise_()
        self.CASA.raise_()
        self.FOO.raise_()
        self.ASOTRU.raise_()
        self.LICHESS.raise_()
        self.pushButton_sig.raise_()
        self.label_3.raise_()
        self.label_A3.raise_()
        self.label_A4.raise_()
        self.label_A2.raise_()
        self.label_2.raise_()
        self.label_1.raise_()
        self.label_A1.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.label_A3_2.raise_()
        self.label_A4_2.raise_()
        self.label_A2_2.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_A1_2.raise_()
        self.label_8.raise_()
        self.label_11.raise_()
        self.label_A3_3.raise_()
        self.label_A4_3.raise_()
        self.label_A2_3.raise_()
        self.label_10.raise_()
        self.label_9.raise_()
        self.label_A1_3.raise_()
        self.label_12.raise_()
        self.label_A2_4.raise_()
        self.label_14.raise_()
        self.label_13.raise_()
        self.label_A1_4.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.radioButton_5.raise_()
        self.radioButton_6.raise_()
        self.radioButton_7.raise_()
        self.radioButton_8.raise_()
        self.radioButton_9.raise_()
        self.radioButton_10.raise_()
        self.radioButton_11.raise_()
        self.radioButton_12.raise_()
        self.radioButton_13.raise_()
        self.radioButton_14.raise_()
        self.label_campeon_2.raise_()
        self.label_campeon.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.CASA.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:26pt;\">#QuedateEnCasa</span></p></body></html>"))
        self.FOO.setText(_translate("Dialog", "<html><head/><body><p>Miguel Herize  @migherize</p></body></html>"))
        self.pushButton_sig.setText(_translate("Dialog", "siguiente"))

import asoaje_rc
import carabobo_rc
import cuartos_rc
import grupos_rc
import lichess_rc
import sorteo_rc
import tru_rc
import vzla_rc
