# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grupos.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_grupos(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1047, 595)
        Dialog.setStyleSheet("background-image: url(:/grupos/grupos.jpg);")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(90, 160, 161, 31))
        self.label_1.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.CASA = QtWidgets.QLabel(Dialog)
        self.CASA.setGeometry(QtCore.QRect(440, 510, 321, 41))
        self.CASA.setStyleSheet("color: rgb(255, 255, 255);")
        self.CASA.setObjectName("CASA")
        self.FOO = QtWidgets.QLabel(Dialog)
        self.FOO.setGeometry(QtCore.QRect(10, 510, 161, 41))
        self.FOO.setStyleSheet("color: rgb(255, 255, 255);")
        self.FOO.setObjectName("FOO")
        self.ASOTRU = QtWidgets.QLabel(Dialog)
        self.ASOTRU.setGeometry(QtCore.QRect(10, 0, 151, 111))
        self.ASOTRU.setStyleSheet("border-image: url(:/asoaje/asotrujillana.jpeg);")
        self.ASOTRU.setText("")
        self.ASOTRU.setObjectName("ASOTRU")
        self.LICHESS = QtWidgets.QLabel(Dialog)
        self.LICHESS.setGeometry(QtCore.QRect(830, 0, 151, 111))
        self.LICHESS.setStyleSheet("border-image: url(:/lichess/lichess.jpeg);")
        self.LICHESS.setText("")
        self.LICHESS.setObjectName("LICHESS")
        self.label_A1 = QtWidgets.QLabel(Dialog)
        self.label_A1.setGeometry(QtCore.QRect(60, 160, 31, 31))
        self.label_A1.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A1.setText("")
        self.label_A1.setObjectName("label_A1")
        self.label_A2 = QtWidgets.QLabel(Dialog)
        self.label_A2.setGeometry(QtCore.QRect(60, 190, 31, 31))
        self.label_A2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A2.setText("")
        self.label_A2.setObjectName("label_A2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 190, 161, 31))
        self.label_2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 250, 161, 31))
        self.label_4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_A3 = QtWidgets.QLabel(Dialog)
        self.label_A3.setGeometry(QtCore.QRect(60, 220, 31, 31))
        self.label_A3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A3.setText("")
        self.label_A3.setObjectName("label_A3")
        self.label_A4 = QtWidgets.QLabel(Dialog)
        self.label_A4.setGeometry(QtCore.QRect(60, 250, 31, 31))
        self.label_A4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_A4.setText("")
        self.label_A4.setObjectName("label_A4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 220, 161, 31))
        self.label_3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(330, 250, 161, 31))
        self.label_8.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(330, 220, 161, 31))
        self.label_7.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(330, 190, 161, 31))
        self.label_6.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_B1 = QtWidgets.QLabel(Dialog)
        self.label_B1.setGeometry(QtCore.QRect(300, 160, 31, 31))
        self.label_B1.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_B1.setText("")
        self.label_B1.setObjectName("label_B1")
        self.label_B2 = QtWidgets.QLabel(Dialog)
        self.label_B2.setGeometry(QtCore.QRect(300, 190, 31, 31))
        self.label_B2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_B2.setText("")
        self.label_B2.setObjectName("label_B2")
        self.label_B3 = QtWidgets.QLabel(Dialog)
        self.label_B3.setGeometry(QtCore.QRect(300, 220, 31, 31))
        self.label_B3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_B3.setText("")
        self.label_B3.setObjectName("label_B3")
        self.label_B4 = QtWidgets.QLabel(Dialog)
        self.label_B4.setGeometry(QtCore.QRect(300, 250, 31, 31))
        self.label_B4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_B4.setText("")
        self.label_B4.setObjectName("label_B4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(330, 160, 161, 31))
        self.label_5.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(580, 250, 161, 31))
        self.label_12.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(580, 220, 161, 31))
        self.label_11.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(580, 190, 161, 31))
        self.label_10.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_C1 = QtWidgets.QLabel(Dialog)
        self.label_C1.setGeometry(QtCore.QRect(550, 160, 31, 31))
        self.label_C1.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_C1.setText("")
        self.label_C1.setObjectName("label_C1")
        self.label_C2 = QtWidgets.QLabel(Dialog)
        self.label_C2.setGeometry(QtCore.QRect(550, 190, 31, 31))
        self.label_C2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_C2.setText("")
        self.label_C2.setObjectName("label_C2")
        self.label_C3 = QtWidgets.QLabel(Dialog)
        self.label_C3.setGeometry(QtCore.QRect(550, 220, 31, 31))
        self.label_C3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_C3.setText("")
        self.label_C3.setObjectName("label_C3")
        self.label_C4 = QtWidgets.QLabel(Dialog)
        self.label_C4.setGeometry(QtCore.QRect(550, 250, 31, 31))
        self.label_C4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_C4.setText("")
        self.label_C4.setObjectName("label_C4")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(580, 160, 161, 31))
        self.label_9.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(820, 250, 161, 31))
        self.label_16.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(820, 190, 161, 31))
        self.label_14.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_D3 = QtWidgets.QLabel(Dialog)
        self.label_D3.setGeometry(QtCore.QRect(790, 220, 31, 31))
        self.label_D3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_D3.setText("")
        self.label_D3.setObjectName("label_D3")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(820, 160, 161, 31))
        self.label_13.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_D4 = QtWidgets.QLabel(Dialog)
        self.label_D4.setGeometry(QtCore.QRect(790, 250, 31, 31))
        self.label_D4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_D4.setText("")
        self.label_D4.setObjectName("label_D4")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(820, 220, 161, 31))
        self.label_15.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_D2 = QtWidgets.QLabel(Dialog)
        self.label_D2.setGeometry(QtCore.QRect(790, 190, 31, 31))
        self.label_D2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_D2.setText("")
        self.label_D2.setObjectName("label_D2")
        self.label_D1 = QtWidgets.QLabel(Dialog)
        self.label_D1.setGeometry(QtCore.QRect(790, 160, 31, 31))
        self.label_D1.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_D1.setText("")
        self.label_D1.setObjectName("label_D1")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(90, 380, 161, 31))
        self.label_18.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_H2 = QtWidgets.QLabel(Dialog)
        self.label_H2.setGeometry(QtCore.QRect(790, 380, 31, 31))
        self.label_H2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_H2.setText("")
        self.label_H2.setObjectName("label_H2")
        self.label_E4 = QtWidgets.QLabel(Dialog)
        self.label_E4.setGeometry(QtCore.QRect(60, 440, 31, 31))
        self.label_E4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_E4.setText("")
        self.label_E4.setObjectName("label_E4")
        self.label_G3 = QtWidgets.QLabel(Dialog)
        self.label_G3.setGeometry(QtCore.QRect(550, 410, 31, 31))
        self.label_G3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_G3.setText("")
        self.label_G3.setObjectName("label_G3")
        self.label_G4 = QtWidgets.QLabel(Dialog)
        self.label_G4.setGeometry(QtCore.QRect(550, 440, 31, 31))
        self.label_G4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_G4.setText("")
        self.label_G4.setObjectName("label_G4")
        self.label_31 = QtWidgets.QLabel(Dialog)
        self.label_31.setGeometry(QtCore.QRect(820, 410, 161, 31))
        self.label_31.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_F2 = QtWidgets.QLabel(Dialog)
        self.label_F2.setGeometry(QtCore.QRect(300, 380, 31, 31))
        self.label_F2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_F2.setText("")
        self.label_F2.setObjectName("label_F2")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(580, 410, 161, 31))
        self.label_27.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_F1 = QtWidgets.QLabel(Dialog)
        self.label_F1.setGeometry(QtCore.QRect(300, 350, 31, 31))
        self.label_F1.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_F1.setText("")
        self.label_F1.setObjectName("label_F1")
        self.label_H3 = QtWidgets.QLabel(Dialog)
        self.label_H3.setGeometry(QtCore.QRect(790, 410, 31, 31))
        self.label_H3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_H3.setText("")
        self.label_H3.setObjectName("label_H3")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(580, 380, 161, 31))
        self.label_26.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(580, 350, 161, 31))
        self.label_25.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_H1 = QtWidgets.QLabel(Dialog)
        self.label_H1.setGeometry(QtCore.QRect(790, 350, 31, 31))
        self.label_H1.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_H1.setText("")
        self.label_H1.setObjectName("label_H1")
        self.label_G2 = QtWidgets.QLabel(Dialog)
        self.label_G2.setGeometry(QtCore.QRect(550, 380, 31, 31))
        self.label_G2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_G2.setText("")
        self.label_G2.setObjectName("label_G2")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(90, 410, 161, 31))
        self.label_19.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(330, 440, 161, 31))
        self.label_24.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_H4 = QtWidgets.QLabel(Dialog)
        self.label_H4.setGeometry(QtCore.QRect(790, 440, 31, 31))
        self.label_H4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_H4.setText("")
        self.label_H4.setObjectName("label_H4")
        self.label_F4 = QtWidgets.QLabel(Dialog)
        self.label_F4.setGeometry(QtCore.QRect(300, 440, 31, 31))
        self.label_F4.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_F4.setText("")
        self.label_F4.setObjectName("label_F4")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(90, 440, 161, 31))
        self.label_20.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(90, 350, 161, 31))
        self.label_17.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(580, 440, 161, 31))
        self.label_28.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(330, 410, 161, 31))
        self.label_23.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_E2 = QtWidgets.QLabel(Dialog)
        self.label_E2.setGeometry(QtCore.QRect(60, 380, 31, 31))
        self.label_E2.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_E2.setText("")
        self.label_E2.setObjectName("label_E2")
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setGeometry(QtCore.QRect(820, 380, 161, 31))
        self.label_30.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(330, 380, 161, 31))
        self.label_22.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_E1 = QtWidgets.QLabel(Dialog)
        self.label_E1.setGeometry(QtCore.QRect(60, 350, 31, 31))
        self.label_E1.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_E1.setText("")
        self.label_E1.setObjectName("label_E1")
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setGeometry(QtCore.QRect(820, 350, 161, 31))
        self.label_29.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_E3 = QtWidgets.QLabel(Dialog)
        self.label_E3.setGeometry(QtCore.QRect(60, 410, 31, 31))
        self.label_E3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_E3.setText("")
        self.label_E3.setObjectName("label_E3")
        self.label_G1 = QtWidgets.QLabel(Dialog)
        self.label_G1.setGeometry(QtCore.QRect(550, 350, 31, 31))
        self.label_G1.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_G1.setText("")
        self.label_G1.setObjectName("label_G1")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(330, 350, 161, 31))
        self.label_21.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setGeometry(QtCore.QRect(820, 440, 161, 31))
        self.label_32.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_F3 = QtWidgets.QLabel(Dialog)
        self.label_F3.setGeometry(QtCore.QRect(300, 410, 31, 31))
        self.label_F3.setStyleSheet("background-image: url(:/grupos/grupos.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_F3.setText("")
        self.label_F3.setObjectName("label_F3")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 280, 91, 31))
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 280, 91, 31))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 280, 91, 31))
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(840, 280, 91, 31))
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 470, 91, 31))
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(350, 470, 91, 31))
        self.pushButton_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(600, 470, 91, 31))
        self.pushButton_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(840, 470, 91, 31))
        self.pushButton_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_sig = QtWidgets.QPushButton(Dialog)
        self.pushButton_sig.setGeometry(QtCore.QRect(850, 510, 111, 41))
        self.pushButton_sig.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_sig.setObjectName("pushButton_sig")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.CASA.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:26pt;\">#QuedateEnCasa</span></p></body></html>"))
        self.FOO.setText(_translate("Dialog", "<html><head/><body><p>Miguel Herize  @migherize</p></body></html>"))
        self.pushButton_2.setText(_translate("Dialog", "Resultados"))
        self.pushButton.setText(_translate("Dialog", "Resultados"))
        self.pushButton_3.setText(_translate("Dialog", "Resultados"))
        self.pushButton_4.setText(_translate("Dialog", "Resultados"))
        self.pushButton_5.setText(_translate("Dialog", "Resultados"))
        self.pushButton_6.setText(_translate("Dialog", "Resultados"))
        self.pushButton_7.setText(_translate("Dialog", "Resultados"))
        self.pushButton_8.setText(_translate("Dialog", "Resultados"))
        self.pushButton_sig.setText(_translate("Dialog", ">> 8vos"))

import asoaje_rc
import grupos_rc
import lichess_rc
import tru_rc
import vzla_rc
import carabobo_rc
import merida_rc
import apure_rc
