# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultadoF.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ResultadoF(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(861, 278)
        Dialog.setStyleSheet("")
        self.refrescar = QtWidgets.QPushButton(Dialog)
        self.refrescar.setGeometry(QtCore.QRect(670, 220, 111, 41))
        self.refrescar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-image: url(:/champions/champions.jpeg);")
        self.refrescar.setObjectName("refrescar")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 10, 861, 291))
        self.label.setStyleSheet("border-image: url(:/champions/champions.jpeg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4_4 = QtWidgets.QLabel(Dialog)
        self.label_4_4.setGeometry(QtCore.QRect(130, 190, 161, 31))
        self.label_4_4.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.label_4_4.setText("")
        self.label_4_4.setObjectName("label_4_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(100, 190, 31, 31))
        self.label_4.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(100, 100, 31, 31))
        self.label_1.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.label_1_1 = QtWidgets.QLabel(Dialog)
        self.label_1_1.setGeometry(QtCore.QRect(130, 100, 161, 31))
        self.label_1_1.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.label_1_1.setText("")
        self.label_1_1.setObjectName("label_1_1")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 130, 31, 31))
        self.label_2.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2_2 = QtWidgets.QLabel(Dialog)
        self.label_2_2.setGeometry(QtCore.QRect(130, 130, 161, 31))
        self.label_2_2.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.label_2_2.setText("")
        self.label_2_2.setObjectName("label_2_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 160, 31, 31))
        self.label_3.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3_3 = QtWidgets.QLabel(Dialog)
        self.label_3_3.setGeometry(QtCore.QRect(130, 160, 161, 31))
        self.label_3_3.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.label_3_3.setText("")
        self.label_3_3.setObjectName("label_3_3")
        self.jugadores = QtWidgets.QLabel(Dialog)
        self.jugadores.setGeometry(QtCore.QRect(130, 70, 161, 31))
        self.jugadores.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.jugadores.setObjectName("jugadores")
        self.R1 = QtWidgets.QLabel(Dialog)
        self.R1.setGeometry(QtCore.QRect(290, 70, 71, 31))
        self.R1.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.R1.setObjectName("R1")
        self.R2 = QtWidgets.QLabel(Dialog)
        self.R2.setGeometry(QtCore.QRect(360, 70, 71, 31))
        self.R2.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.R2.setObjectName("R2")
        self.R3 = QtWidgets.QLabel(Dialog)
        self.R3.setGeometry(QtCore.QRect(430, 70, 71, 31))
        self.R3.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.R3.setObjectName("R3")
        self.R4 = QtWidgets.QLabel(Dialog)
        self.R4.setGeometry(QtCore.QRect(500, 70, 71, 31))
        self.R4.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.R4.setObjectName("R4")
        self.Puntaje = QtWidgets.QLabel(Dialog)
        self.Puntaje.setGeometry(QtCore.QRect(570, 70, 71, 31))
        self.Puntaje.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.Puntaje.setObjectName("Puntaje")
        self.numero = QtWidgets.QLabel(Dialog)
        self.numero.setGeometry(QtCore.QRect(100, 70, 31, 31))
        self.numero.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.numero.setObjectName("numero")
        self.R1_1 = QtWidgets.QLabel(Dialog)
        self.R1_1.setGeometry(QtCore.QRect(290, 100, 71, 31))
        self.R1_1.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.R1_1.setObjectName("R1_1")
        self.R2_2 = QtWidgets.QLabel(Dialog)
        self.R2_2.setGeometry(QtCore.QRect(360, 130, 71, 31))
        self.R2_2.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.R2_2.setObjectName("R2_2")
        self.R3_3 = QtWidgets.QLabel(Dialog)
        self.R3_3.setGeometry(QtCore.QRect(430, 160, 71, 31))
        self.R3_3.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.R3_3.setObjectName("R3_3")
        self.R4_5 = QtWidgets.QLabel(Dialog)
        self.R4_5.setGeometry(QtCore.QRect(500, 190, 71, 31))
        self.R4_5.setStyleSheet("background-color: rgb(141, 141, 141);\n"
"color: rgb(255, 255, 255);")
        self.R4_5.setObjectName("R4_5")
        self.lineEdit_1_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_1_2.setGeometry(QtCore.QRect(290, 130, 71, 31))
        self.lineEdit_1_2.setObjectName("lineEdit_1_2")
        self.lineEdit_1_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_1_3.setGeometry(QtCore.QRect(290, 160, 71, 31))
        self.lineEdit_1_3.setObjectName("lineEdit_1_3")
        self.lineEdit_1_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_1_4.setGeometry(QtCore.QRect(290, 190, 71, 31))
        self.lineEdit_1_4.setObjectName("lineEdit_1_4")
        self.lineEdit_4_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4_3.setGeometry(QtCore.QRect(500, 160, 71, 31))
        self.lineEdit_4_3.setObjectName("lineEdit_4_3")
        self.lineEdit_4_1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4_1.setGeometry(QtCore.QRect(500, 100, 71, 31))
        self.lineEdit_4_1.setObjectName("lineEdit_4_1")
        self.lineEdit_4_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4_2.setGeometry(QtCore.QRect(500, 130, 71, 31))
        self.lineEdit_4_2.setObjectName("lineEdit_4_2")
        self.resultado3 = QtWidgets.QLineEdit(Dialog)
        self.resultado3.setGeometry(QtCore.QRect(570, 160, 71, 31))
        self.resultado3.setObjectName("resultado3")
        self.resultado1 = QtWidgets.QLineEdit(Dialog)
        self.resultado1.setGeometry(QtCore.QRect(570, 100, 71, 31))
        self.resultado1.setObjectName("resultado1")
        self.resultado2 = QtWidgets.QLineEdit(Dialog)
        self.resultado2.setGeometry(QtCore.QRect(570, 130, 71, 31))
        self.resultado2.setObjectName("resultado2")
        self.lineEdit_2_1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2_1.setGeometry(QtCore.QRect(360, 100, 71, 31))
        self.lineEdit_2_1.setObjectName("lineEdit_2_1")
        self.resultado4 = QtWidgets.QLineEdit(Dialog)
        self.resultado4.setGeometry(QtCore.QRect(570, 190, 71, 31))
        self.resultado4.setObjectName("resultado4")
        self.lineEdit_2_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2_3.setGeometry(QtCore.QRect(360, 160, 71, 31))
        self.lineEdit_2_3.setObjectName("lineEdit_2_3")
        self.lineEdit_3_1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3_1.setGeometry(QtCore.QRect(430, 100, 71, 31))
        self.lineEdit_3_1.setObjectName("lineEdit_3_1")
        self.lineEdit_3_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3_2.setGeometry(QtCore.QRect(430, 130, 71, 31))
        self.lineEdit_3_2.setObjectName("lineEdit_3_2")
        self.lineEdit_2_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2_4.setGeometry(QtCore.QRect(360, 190, 71, 31))
        self.lineEdit_2_4.setObjectName("lineEdit_2_4")
        self.lineEdit_3_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3_4.setGeometry(QtCore.QRect(430, 190, 71, 31))
        self.lineEdit_3_4.setObjectName("lineEdit_3_4")
        self.label.raise_()
        self.refrescar.raise_()
        self.label_4_4.raise_()
        self.label_4.raise_()
        self.label_1.raise_()
        self.label_1_1.raise_()
        self.label_2.raise_()
        self.label_2_2.raise_()
        self.label_3.raise_()
        self.label_3_3.raise_()
        self.jugadores.raise_()
        self.R1.raise_()
        self.R2.raise_()
        self.R3.raise_()
        self.R4.raise_()
        self.Puntaje.raise_()
        self.numero.raise_()
        self.R1_1.raise_()
        self.R2_2.raise_()
        self.R3_3.raise_()
        self.R4_5.raise_()
        self.lineEdit_1_2.raise_()
        self.lineEdit_1_3.raise_()
        self.lineEdit_1_4.raise_()
        self.lineEdit_4_3.raise_()
        self.lineEdit_4_1.raise_()
        self.lineEdit_4_2.raise_()
        self.resultado3.raise_()
        self.resultado1.raise_()
        self.resultado2.raise_()
        self.lineEdit_2_1.raise_()
        self.resultado4.raise_()
        self.lineEdit_2_3.raise_()
        self.lineEdit_3_1.raise_()
        self.lineEdit_3_2.raise_()
        self.lineEdit_2_4.raise_()
        self.lineEdit_3_4.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.refrescar.setText(_translate("Dialog", "actualizar"))
        self.jugadores.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Jugadores</span></p></body></html>"))
        self.R1.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">R1</p></body></html>"))
        self.R2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">R2</p></body></html>"))
        self.R3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">R3</p></body></html>"))
        self.R4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">R4</p></body></html>"))
        self.Puntaje.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Puntaje</p></body></html>"))
        self.numero.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">n</p></body></html>"))
        self.R1_1.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">X</p></body></html>"))
        self.R2_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">X</p></body></html>"))
        self.R3_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">X</p></body></html>"))
        self.R4_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">X</p></body></html>"))

import apure_rc
import carabobo_rc
import champions_rc
import merida_rc
