# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultado.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Resultado(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(844, 281)
        Dialog.setStyleSheet("")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(70, 20, 721, 151))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        self.octavos = QtWidgets.QPushButton(Dialog)
        self.octavos.setGeometry(QtCore.QRect(670, 220, 111, 41))
        self.octavos.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-image: url(:/champions/champions.jpeg);")
        self.octavos.setObjectName("octavos")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-10, -10, 861, 291))
        self.label.setStyleSheet("border-image: url(:/champions/champions.jpeg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.tableWidget.raise_()
        self.octavos.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Jugadores"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "ELO"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "R1"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "R2"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "R3"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "R4"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Resultado"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Dialog", "X"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("Dialog", "X"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("Dialog", "X"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("Dialog", "X"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.octavos.setText(_translate("Dialog", "Regresar"))

import champions_rc
